# Generated by Django 5.2.7 on 2026-04-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('preco_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=False)),
                ('imagem_capa', models.ImageField(upload_to='fotos_servico/')),
                ('data_admissao', models.DateTimeField(blank=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='servicos.categoria')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='localizacao.cidade')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='localizacao.endereco')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='usuarios.parceiro')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'db_table': 'servico',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_imagem', models.ImageField(upload_to='imagens_servicos/')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_servico', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Imagem do Serviço',
                'verbose_name_plural': 'Imagens dos Serviços',
                'db_table': 'imagem_servico',
                'ordering': ['servico__nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('dia_semana', models.CharField(choices=[('DOM', 'Domingo'), ('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado')], max_length=3)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_funcionamento', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'db_table': 'horario_funcionamento',
                'ordering': ['servico__nome', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='servicos.categoria')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ['nome', 'categoria__nome'],
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='tags',
            field=models.ManyToManyField(related_name='servicos', to='servicos.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('nome', 'categoria'), name='tag_unico_nome_categoria'),
        ),
        migrations.AddConstraint(
            model_name='servico',
            constraint=models.UniqueConstraint(fields=('nome', 'parceiro'), name='servico_unico_nome_parceiro'),
        ),
    ]
