# Generated by Django 5.2.7 on 2026-04-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
                'ordering': ['logradouro', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('logradouro', 'numero'), name='endereco_unico_logradouro_numero')],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='localizacao.estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
                'ordering': ['nome', 'estado__sigla'],
            },
        ),
        migrations.CreateModel(
            name='ImagemCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_imagem', models.ImageField(upload_to='imagens_cidades/')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='localizacao.cidade')),
            ],
            options={
                'verbose_name': 'Imagem da Cidade',
                'verbose_name_plural': 'Imagens das Cidades',
                'db_table': 'imagem_cidade',
                'ordering': ['cidade__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('nome', 'estado'), name='cidade_unico_nome_estado'),
        ),
    ]
