# Generated by Django 5.2.7 on 2026-04-10 00:59

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models.usuario
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('url_instagram', models.URLField(blank=True, null=True, unique=True)),
                ('url_facebook', models.URLField(blank=True, null=True, unique=True)),
                ('url_x', models.URLField(blank=True, null=True, unique=True)),
                ('url_tiktok', models.URLField(blank=True, null=True, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('RUDIERO', 'Rudiero'), ('PARCEIRO', 'Parceiro'), ('MODERADOR', 'Moderador'), ('ADMINISTRADOR', 'Administrador')], default='RUDIERO', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['username'],
            },
            managers=[
                ('objects', usuarios.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ativo', models.BooleanField(default=False)),
                ('data_admissao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'db_table': 'parceiro',
                'ordering': ['username'],
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', usuarios.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rudiero',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro Não Informar')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Rudiero',
                'verbose_name_plural': 'Rudieros',
                'db_table': 'rudiero',
                'ordering': ['username'],
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', usuarios.models.usuario.UsuarioManager()),
            ],
        ),
    ]
