# Generated by Django 5.2.7 on 2026-04-10 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
        ('servicos', '0001_initial'),
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateField()),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PRIVADO', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'db_table': 'roteiro',
                'ordering': ['viagem__nome', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DiaRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField()),
                ('servicos', models.ManyToManyField(related_name='dias_roteiro', to='servicos.servico')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_roteiro', to='viagem.roteiro')),
            ],
            options={
                'verbose_name': 'Dia do Roteiro',
                'verbose_name_plural': 'Dias do Roteiro',
                'db_table': 'dia_roteiro',
                'ordering': ['roteiro__viagem__nome', 'dia'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('dias', models.PositiveIntegerField()),
                ('orcamento_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('viajantes_adultos', models.PositiveIntegerField(default=1)),
                ('viajantes_criancas', models.PositiveIntegerField(default=0)),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], default='PRIVADO', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_destino', to='localizacao.cidade')),
                ('rudiero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='usuarios.rudiero')),
                ('servicos', models.ManyToManyField(related_name='viagens', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'viagem',
                'ordering': ['nome', '-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='roteiro',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to='viagem.viagem'),
        ),
    ]
