# Generated by Django 5.2.7 on 2026-04-10 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_moderador', models.TextField(blank=True, null=True)),
                ('status_proposta', models.CharField(choices=[('EA', 'Em Análise'), ('AP', 'Aprovada'), ('RP', 'Reprovada')], default='EA', max_length=2)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('moderador', models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario__in': ['MODERADOR', 'ADMINISTRADOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_analisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'db_table': 'proposta',
                'ordering': ['status_proposta', '-data_criacao'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='proposta_content_605e54_idx'), models.Index(fields=['status_proposta', 'data_criacao'], name='proposta_status__081bf7_idx')],
            },
        ),
    ]
